language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
sudo: false
install:
  - pip install -q -r requirements.dev.txt
script:
  - coverage run --source=awaredatetime setup.py test
  - flake8 awaredatetime tests
after_success:
  coveralls
